version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=sxannyy
      - POSTGRES_PASSWORD=7721
      - POSTGRES_DB=mobiledogs
    ports:
      - "5432:5432"
    networks:
      - custom

  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    enviroment:
      - POSTGRES_USER=sxannyy_test
      - POSTGRES_PASSWORD=7721_test
      - POSTGRES_DB=mobiledogs_test
    ports:
        - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge