"""test running migrations

Revision ID: f5dcb2487125
Revises: d6723bf0e372
Create Date: 2024-05-30 08:11:35.824227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dcb2487125'
down_revision = 'd6723bf0e372'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
