"""test running migrations

Revision ID: 03da8ae1f0ec
Revises: 51e105e4fee8
Create Date: 2024-05-29 07:02:17.764005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03da8ae1f0ec'
down_revision: Union[str, None] = '51e105e4fee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
