"""test running migrations

Revision ID: 1ef0eb9e5d15
Revises: 01ca46c1d75a
Create Date: 2024-05-29 07:11:35.137748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef0eb9e5d15'
down_revision: Union[str, None] = '01ca46c1d75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
