"""test running migrations

Revision ID: 57ad0de2d48a
Revises: 8f4bdbc21041
Create Date: 2024-05-29 08:01:20.604728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ad0de2d48a'
down_revision: Union[str, None] = '8f4bdbc21041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
